name: batter
channels:
  - conda-forge
  - defaults
dependencies:
  # Conda dependencies
  - pip
  - ambertools >=23.6
  - openbabel
  - pandas
  - prettypyplot
  - seaborn
  - loguru
  - pydantic >=2.11.7
  - click  >=8.2.0
  - vmd
  - libgl
  - apbs
  - MDAnalysis >=2.9.0
  - jax
  - pymbar >4.0
  # dask distributed for analysis
  - dask
  - dask-jobqueue
  - distributed
  # openfe
  - gufe >=1.7.0
  - openff-interchange
  - openff-interchange-base
  - openff-toolkit-base >=0.16.2
  - kartograf
  # Tests
  - pytest
  - pytest-xdist
  - pytest-cov
  - pytest-snapshot
  
  - pip:
    - nglview  
  # optional
  # - unipka
