name: batter
channels:
  - conda-forge
  - defaults
dependencies:
  # Conda dependencies
  - ambertools=23.6
  - openbabel
  - pandas
  - prettypyplot
  - seaborn
  - loguru
  - pydantic>=2.11.7
  - click
  - pandas
  - alchemlyb
  - vmd
  # dask distributed for analysis
  - dask
  - dask-jobqueue
  - distributed
  # Tests
  - pytest
  - pytest-xdist
  - pytest-cov
  - pytest-snapshot
  
  - pip:
    - nglview  